server:
  port: 8201
  #  servlet:
  #    session:
  #      timeout: 10
  #      cookie:
  #        max-age: 10
db:
  hostname: localhost
  username: root
  password: 12345678
  schema: mall

spring:
  application:
    name: mail-merchant
  r2dbc:
    url: r2dbcs:mysql://${db.hostname}:3306/${db.schema}?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: ${db.username}
    password: ${db.password}
    pool:
      enabled: true
      initial-size: 5
      max-size: 5
      max-idle-time: 10m
  #      validation-query: ping
  #    properties:
  #      connectTimeout: 1m
  flyway:
    url: jdbc:mysql://${db.hostname}:3306/${db.schema}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    validate-on-migrate: false
  main:
    allow-bean-definition-overriding: true
  session:
    timeout: 36000

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
logging:
  level:
    root: debug
  file:
    max-history: 2
peacetrue:
  spring:
    security:
      ignored-urls: [ '/members/register','/members/exists','/index.html','/favicon.ico','/manifest.json','/logo192.png','/static/**' ]
  enum:
    base-package-paths: com.github.peacetrue
  operator:
    pointcut:
      expression: 'execution(* cn.ruyijiaoyu.mall..*Service.*(*,..))||execution(* com.github.peacetrue..*Service.*(*,..))'
  file:
    #    base-path: /Users/xiayx/Documents/haohan/mall-server/01-upload
    base-path: /Users/xiayx/Documents/tuchong/mall/01-upload
