server:
  port: 8200

#  servlet:
#    session:
#      timeout: 10
#      cookie:
#        max-age: 10

logging:
  level:
    com.github.peacetrue: debug
    org.springframework: debug
  file:
    max-history: 2

db:
  hostname: localhost
  username: root
  password: 1qw2!QW@
  schema: mall

spring:
  application:
    name: mall-platform
  r2dbc:
    url: r2dbcs:mysql://${db.hostname}:3306/${db.schema}?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: ${db.username}
    password: ${db.password}
    pool:
      enabled: true
      initial-size: 5
      max-size: 5
      max-idle-time: 10m
  #      validation-query: ping
  #    properties:
  #      connectTimeout: 1m
  flyway:
    url: jdbc:mysql://${db.hostname}:3306/${db.schema}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    validate-on-migrate: false
  main:
    allow-bean-definition-overriding: true
  session:
    timeout: 36000
  jackson:
    serialization:
      WRITE_ENUMS_USING_INDEX: true
#    deserialization:


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
peacetrue:
  spring:
    security:
      ignored-urls: [ '/users/register','/users/exists','/index.html','/favicon.ico','/manifest.json','/logo192.png','/static/**' ]
  enum:
    base-package-paths: com.github.peacetrue
  operator:
    pointcut:
      expression: 'execution(* com.github.peacetrue..*Service.*(*,..))'
  file:
    base-path: /Users/xiayx/Documents/tuchong/mall/01-upload
    host: https://peacetrue.cn/platform/files/
  jackson:
    mix-ins:
      com.github.peacetrue.user.UserVO: com.github.peacetrue.convention.PasswordIgnorer
      com.github.peacetrue.merchant.MerchantVO: com.github.peacetrue.convention.PasswordIgnorer
      com.github.peacetrue.member.MemberVO: com.github.peacetrue.convention.PasswordIgnorer
